### ISSUE TITLE
下载错误

### ISSUE THREAD

**Issue by Zuiliha** [xiahualiu/lethal_zh_mod#2]
在thunderstore下载到100%就停止了,my mods列表里也没有

**Comment by Zuiliha** [comment]
![Overwolf_RufPxyRF3z](https://github.com/xiahualiu/lethal_zh_mod/assets/154461895/43f01cf9-52e1-4991-8e46-499cfa7b5c72)

**Comment by sbzlzh** [comment]
> 在thunderstore下载到100%就停止了,my mods列表里也没有

我也遇到过，但是我重下之后就好了：）

**Comment by SilentC1ty** [comment]
我也卡100%

**Comment by Rayluoluoluo** [comment]
same thunder store

**Comment by xiahualiu** [comment]
去Setting里面点Debugging，然后点下面的Clean mod cache，重新下载就应该好了。
这个应该是R2modman本身的问题，应该是下载的时候卡了。
